class Champion:

    def __init__(self, name, hasMana, isRanged) -> None:
        #name = string
        #hasMana = bool
        #isRanged = bool
        self.name = name
        self.hasMana = hasMana
        self.isRanged = isRanged

class Mythic:
    def __init__(self, name, hasMana, hasManaRegen) -> None:
        self.name = name
        self.hasMana = hasMana
        self.hasManaRegen = hasManaRegen

class Boots:
    def __init__(self, name) -> None:
        self.name = name

class Legendary:
    def __init__(self, name, hasMana, hasManaRegen) -> None:
        self.name = name
        self.hasMana = hasMana
        self.hasManaRegen = hasManaRegen

class Runes:
    def __init__(self, name,row,tree) -> None:
        self.name = name
        self.row = row
        self.tree = tree

champion_pool = []  #✓
boots_pool = []
mythic_pool = []
legendary_pool = []
runes_pool = []


#Champs
champion_pool.append(Champion("Aatrox", False, False))
champion_pool.append(Champion("Ahri", True, True))
champion_pool.append(Champion("Akali", False, False))
champion_pool.append(Champion("Akshan", True, False))
champion_pool.append(Champion("Alistar", True, False))
champion_pool.append(Champion("Amumu", True, False))
champion_pool.append(Champion("Anivia", True, True))
champion_pool.append(Champion("Annie", True, True))
champion_pool.append(Champion("Aphelios", True, True))
champion_pool.append(Champion("Ashe", True, True))
champion_pool.append(Champion("Aurelion Sol", True, True))
champion_pool.append(Champion("Azir", True, True))
champion_pool.append(Champion("Bard", True, True))
champion_pool.append(Champion("Bel'Veth", False, False))
champion_pool.append(Champion("Blitzcrank", True, False))
champion_pool.append(Champion("Brand", True, True))
champion_pool.append(Champion("Caitlyn", True, True))
champion_pool.append(Champion("Camille", True, False))
champion_pool.append(Champion("Cassiopeia", True, True))
champion_pool.append(Champion("Cho'Gath", True, False))
champion_pool.append(Champion("Corki", True, True))
champion_pool.append(Champion("Darius", True, False))
champion_pool.append(Champion("Diana", True, False))
champion_pool.append(Champion("Dr. Mundo", True, False))
champion_pool.append(Champion("Draven", True, False))
champion_pool.append(Champion("Ekko", True, False))
champion_pool.append(Champion("Elise", True, True))
champion_pool.append(Champion("Evelynn", True, False))
champion_pool.append(Champion("Ezreal", True, True))
champion_pool.append(Champion("Fiddlesticks", True, False))
champion_pool.append(Champion("Fiora", True, False))
champion_pool.append(Champion("Fizz", True, False))
champion_pool.append(Champion("Galio", True, False))
champion_pool.append(Champion("Gangplank", True, False))
champion_pool.append(Champion("Gnar", False, True))
champion_pool.append(Champion("Gragas", True, False))
champion_pool.append(Champion("Graves", True, True))
champion_pool.append(Champion("Gwen", True, False))
champion_pool.append(Champion("Hecarim", True, False))
champion_pool.append(Champion("Heimerdinger", True, True))
champion_pool.append(Champion("Illaoi", True, False))
champion_pool.append(Champion("Irelia", True, False))
champion_pool.append(Champion("Ivern", True, True))
champion_pool.append(Champion("Janna", True, True))
champion_pool.append(Champion("Jarvan IV", True, False))
champion_pool.append(Champion("Jax", True, False))
champion_pool.append(Champion("Jhin", True, True))
champion_pool.append(Champion("Jinx", True, True))
champion_pool.append(Champion("Kai'Sa", True, True))
champion_pool.append(Champion("Kalista", True, True))
champion_pool.append(Champion("Karma", True, True))
champion_pool.append(Champion("Karthus", True, True))
champion_pool.append(Champion("Kassadin", True, True))
champion_pool.append(Champion("Katarina", False, False))
champion_pool.append(Champion("Kayle", True, True))
champion_pool.append(Champion("Kayn", True, False))
champion_pool.append(Champion("Kennen", False, True))
champion_pool.append(Champion("Kha'Zix", True, False))
champion_pool.append(Champion("Kindred", True, True))
champion_pool.append(Champion("Kled", False, True))
champion_pool.append(Champion("Kog'Maw", True, True))
champion_pool.append(Champion("LeBlanc", True, True))
champion_pool.append(Champion("Lee Sin", False, False))
champion_pool.append(Champion("Leona", True, False))
champion_pool.append(Champion("Lillia", True, True))
champion_pool.append(Champion("Lissandra", True, True))
champion_pool.append(Champion("Lux", True, True))
champion_pool.append(Champion("Malphite", True, False))
champion_pool.append(Champion("Malzahar", True, True))
champion_pool.append(Champion("Maokai", True, False))
champion_pool.append(Champion("Master Yi", True, False))
champion_pool.append(Champion("Miss Fortune", True, True))
champion_pool.append(Champion("Mordekaiser", False, False))
champion_pool.append(Champion("Morgana", True, True))
champion_pool.append(Champion("Nami", True, True))
champion_pool.append(Champion("Nasus", True, False))
champion_pool.append(Champion("Nautilus", True, False))
champion_pool.append(Champion("Neeko", True, True))
champion_pool.append(Champion("Nidalee", True, True))
champion_pool.append(Champion("Nilah", True, True))
champion_pool.append(Champion("Nocturne", True, False))
champion_pool.append(Champion("Nunu & Willump", True, False))
champion_pool.append(Champion("Olaf", True, False))
champion_pool.append(Champion("Orianna", True, True))
champion_pool.append(Champion("Zyra ", True, True))
champion_pool.append(Champion("Zoe ", True, True))
champion_pool.append(Champion("Zilean ", True, True))
champion_pool.append(Champion("Ziggs ", True, True))
champion_pool.append(Champion("Zeri ", True, True))
champion_pool.append(Champion("Zed ", False, False))
champion_pool.append(Champion("Zac ", False, False))
champion_pool.append(Champion("Yuumi ", True, True))
champion_pool.append(Champion("Yorick ", True, False))
champion_pool.append(Champion("Yone ", False, False))
champion_pool.append(Champion("Yasuo ", False, False))
champion_pool.append(Champion("Xin Zhao ", True, False))
champion_pool.append(Champion("Xerath ", True, True))
champion_pool.append(Champion("Xayah ", True, True))
champion_pool.append(Champion("Wukong ", True, False))
champion_pool.append(Champion("Warwick ", True, False))
champion_pool.append(Champion("Volibear ", True, False))
champion_pool.append(Champion("Vladimir ", False, True))
champion_pool.append(Champion("Viktor ", True, True))
champion_pool.append(Champion("Viego ", False, False))
champion_pool.append(Champion("Vi ", True, False))
champion_pool.append(Champion("Vex ", True, True))
champion_pool.append(Champion("Vel'Koz ", True, True))
champion_pool.append(Champion("Veigar ", True, True))
champion_pool.append(Champion("Vayne ", True, True))
champion_pool.append(Champion("Varus ", True, True))
champion_pool.append(Champion("Urgot ", True, True))
champion_pool.append(Champion("Udyr ", True, False))
champion_pool.append(Champion("Twitch ", True, True))
champion_pool.append(Champion("Twisted Fate ", True, True))
champion_pool.append(Champion("Tryndamere ", False,False))
champion_pool.append(Champion("Trundle ", True, False))
champion_pool.append(Champion("Thresh ", True, True))
champion_pool.append(Champion("Teemo ", True, True))
champion_pool.append(Champion("Taric ", True, False))
champion_pool.append(Champion("Talon ", True, False))
champion_pool.append(Champion("Taliyah ", True, True))
champion_pool.append(Champion("Tahm Kench ", True, False))
champion_pool.append(Champion("Syndra ", True, True))
champion_pool.append(Champion("Sylas ", True, False))
champion_pool.append(Champion("Swain ", True, True))
champion_pool.append(Champion("Soraka ", True, True))
champion_pool.append(Champion("Sona ", True, True))
champion_pool.append(Champion("Skarner", True, False))
champion_pool.append(Champion("Sivir ", True, True))
champion_pool.append(Champion("Sion ", True, False))
champion_pool.append(Champion("Singed ", True, False))
champion_pool.append(Champion("Shyvanna ", False,False))
champion_pool.append(Champion("Shen ", False,False))
champion_pool.append(Champion("Shaco ", True, False))
champion_pool.append(Champion("Sett ", False,False))
champion_pool.append(Champion("Seraphine ", True,True))
champion_pool.append(Champion("Senna ", True,True))
champion_pool.append(Champion("Sejuani ", True,False))
champion_pool.append(Champion("Samira ", True,True))
champion_pool.append(Champion("Ryze ", True,True))
champion_pool.append(Champion("Rumble ", False,False))
champion_pool.append(Champion("Riven ", False,False))
champion_pool.append(Champion("Rengar", False,False))
champion_pool.append(Champion("Renekton", False,False))
champion_pool.append(Champion("Renata Glasc", True,True))
champion_pool.append(Champion("Rell", True,False))
champion_pool.append(Champion("Rek'Sai", False,False))
champion_pool.append(Champion("Rammus", True,False))
champion_pool.append(Champion("Rakan", True,False))
champion_pool.append(Champion("Quinn", True,True))
champion_pool.append(Champion("Qiyana", True,False))
champion_pool.append(Champion("Pyke", True,False))
champion_pool.append(Champion("Poppy", True,False))
champion_pool.append(Champion("Pantheon", True,False))
champion_pool.append(Champion("Ornn", True,False))

#Boots
boots_pool.append(Boots("Boots of Speed")) #Tier 1 boots
boots_pool.append(Boots("Berserker's Greaves"))
boots_pool.append(Boots("Mobility Boots"))
boots_pool.append(Boots("Boots of Swiftness"))
boots_pool.append(Boots("Ionian Boots of Lucidity"))
boots_pool.append(Boots("Mercury's Threads"))
boots_pool.append(Boots("Plated Steelcaps"))
boots_pool.append(Boots("Sorcerer's Shoes"))

#Mythics
mythic_pool.append(Mythic("Eclipse",False,False))
mythic_pool.append(Mythic("Crown of the Shattered Queen",True,False))
mythic_pool.append(Mythic("Duskblade of Draktharr",False,False))
mythic_pool.append(Mythic("Evenshroud",False,False))
mythic_pool.append(Mythic("Everfrost",True,False))
mythic_pool.append(Mythic("Frostfire Gauntlet",False,False))
mythic_pool.append(Mythic("Galeforce",False,False))
mythic_pool.append(Mythic("Goredrinker",False,False))
mythic_pool.append(Mythic("Hextech Rocketbelt",False,False))
mythic_pool.append(Mythic("Immortal Shieldbow",False,False))
mythic_pool.append(Mythic("Imperial Mandate",False,True))
mythic_pool.append(Mythic("Kraken Slayer",False,False))
mythic_pool.append(Mythic("Liandry's Anguish",True,False))
mythic_pool.append(Mythic("Locket of the Iron Solari",False,False))
mythic_pool.append(Mythic("Luden's Tempest",True,False))
mythic_pool.append(Mythic("Moonstone Renewer",False,True))
mythic_pool.append(Mythic("Night Harvester",False,False))
mythic_pool.append(Mythic("Prowler's Claw",False,False))
mythic_pool.append(Mythic("Riftmaker",False,False))
mythic_pool.append(Mythic("Shurelya's Battlesong",False,True))
mythic_pool.append(Mythic("Stridebreaker",False,False))
mythic_pool.append(Mythic("Sunfire Aegis",False,False))
mythic_pool.append(Mythic("Trinity Force",False,False))
mythic_pool.append(Mythic("Turbo Chemtank",False,False))

#Legendary
legendary_pool.append(Legendary("Abyssal Mask"))
legendary_pool.append(Legendary("Anathema's Chains"))
legendary_pool.append(Legendary("Archangel's Staff")) #tear unfinished
legendary_pool.append(Legendary("Arden Censer"))
legendary_pool.append(Legendary("Axiom Arc"))
legendary_pool.append(Legendary("Banshee's Veil"))
legendary_pool.append(Legendary("Black Cleaver"))
legendary_pool.append(Legendary("Black Mist Scythe")) #support starter
legendary_pool.append(Legendary("Blade of the Ruined King"))
legendary_pool.append(Legendary("Bloodthirster"))
legendary_pool.append(Legendary("Bulkward of the Mountain")) #support starter
legendary_pool.append(Legendary("Chempunk Chainsword"))
legendary_pool.append(Legendary("Chemptech Putrifier"))
legendary_pool.append(Legendary("Cosmic Drive"))
legendary_pool.append(Legendary("Dead Man's Plate"))
legendary_pool.append(Legendary("Death's Dance"))
legendary_pool.append(Legendary("Demonic Embrace"))
legendary_pool.append(Legendary("Edge of Night"))
legendary_pool.append(Legendary("Essence Reaver"))
legendary_pool.append(Legendary("Fimbulwinter")) #tear finished
legendary_pool.append(Legendary("Force of Nature"))
legendary_pool.append(Legendary("Frozen Heart"))
legendary_pool.append(Legendary("Gargoyle Stoneplate"))
legendary_pool.append(Legendary("Guardian Angel"))
legendary_pool.append(Legendary("Guinsoo's Rageblade"))
legendary_pool.append(Legendary("Horizon Focus"))
legendary_pool.append(Legendary("Hullbreaker"))
legendary_pool.append(Legendary("Infinity Edge"))
legendary_pool.append(Legendary("Knight's Vow"))
legendary_pool.append(Legendary("Lich Bane"))
legendary_pool.append(Legendary("Lord Dominik's Regards"))
legendary_pool.append(Legendary("Manamune")) #tear unfinished
legendary_pool.append(Legendary("Maw of Malmortius"))
legendary_pool.append(Legendary("Mejai's Soulstealer"))
legendary_pool.append(Legendary("Mercurial Scimitar"))
legendary_pool.append(Legendary("Mikael's Blessing"))
legendary_pool.append(Legendary("Morellonomicon"))
legendary_pool.append(Legendary("Mortal Reminder"))
legendary_pool.append(Legendary("Muramana")) #tear finished
legendary_pool.append(Legendary("Nashor's Tooth"))
legendary_pool.append(Legendary("Navori Quickblades"))
legendary_pool.append(Legendary("Pauldrons of Whiterock"))
legendary_pool.append(Legendary("Phantom Dancer"))
legendary_pool.append(Legendary("Rabadon's Deathcap"))
legendary_pool.append(Legendary("Randuin's Omen"))
legendary_pool.append(Legendary("Rapid Firecannon"))
legendary_pool.append(Legendary("Ravenous Hydra"))
legendary_pool.append(Legendary("Redemption"))
legendary_pool.append(Legendary("Runnan's Hurricane"))
legendary_pool.append(Legendary("Rylai's Crystal Scepter"))
legendary_pool.append(Legendary("Seraph's Embrace")) # tear finished
legendary_pool.append(Legendary("Serpent's Fang"))
legendary_pool.append(Legendary("Serylda's Grudge"))
legendary_pool.append(Legendary("Shadowflame"))
legendary_pool.append(Legendary("Shard of True Ice"))
legendary_pool.append(Legendary("Silvermere Dawn"))
legendary_pool.append(Legendary("Spirit Visage"))
legendary_pool.append(Legendary("Staff of Flowing Water"))
legendary_pool.append(Legendary("Sterak's Gage"))
legendary_pool.append(Legendary("Stormrazor"))
legendary_pool.append(Legendary("The Collector"))
legendary_pool.append(Legendary("Thronmail"))
legendary_pool.append(Legendary("Titanic Hydra"))
legendary_pool.append(Legendary("Umbral Glaive"))
legendary_pool.append(Legendary("Vigilant Wardstone")
legendary_pool.append(Legendary("Void Staff")))
legendary_pool.append(Legendary("Warmog's Armor"))
legendary_pool.append(Legendary("Winter's Approach")) #tear unfinished
legendary_pool.append(Legendary("Wit's End"))
legendary_pool.append(Legendary("Youmuu's Ghostblade"))
legendary_pool.append(Legendary("Zeke's Convergence"))
legendary_pool.append(Legendary("Zhonya's Hourglass"))

#runes
runes_pool.append(Runes("Press the Attack",1,"Precision"))
runes_pool.append(Runes("Lethal Tempo",1,"Precision"))
runes_pool.append(Runes("Fleet Footwork",1,"Precision"))
runes_pool.append(Runes("Conqueror",1,"Precision"))
runes_pool.append(Runes("Overheal",2,"Precision"))
runes_pool.append(Runes("Triumph",2,"Precision"))
runes_pool.append(Runes("Presence of Mind",2,"Precision"))
runes_pool.append(Runes("Legend:Alacrity",3,"Precision"))
runes_pool.append(Runes("Legend:Tenacity",3,"Precision"))
runes_pool.append(Runes("Legend:Bloodline",3,"Precision"))
runes_pool.append(Runes("Coup de Grace",4,"Precision"))
runes_pool.append(Runes("Cut Down",4,"Precision"))
runes_pool.append(Runes("Last Stand",4,"Precision"))
